"use client";

import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

export type Language = "ko" | "en" | "ja" | "es" | "zh";

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
    lang: "ko",
    setLang: () => { },
    t: (key: string) => key,
});

export function useLanguage() {
    return useContext(LanguageContext);
}

export const LANGUAGES: { id: Language; label: string; flag: string }[] = [
    { id: "ko", label: "한국어", flag: "🇰🇷" },
    { id: "en", label: "English", flag: "🇺🇸" },
    { id: "ja", label: "日本語", flag: "🇯🇵" },
    { id: "es", label: "Español", flag: "🇪🇸" },
    { id: "zh", label: "中文", flag: "🇨🇳" },
];

// ──────────────────── Translation Dictionaries ────────────────────

const translations: Record<Language, Record<string, string>> = {
    ko: {
        // Header
        "header.title": "Your To-Do",
        "header.subtitle.list": "오늘의 할 일",
        "header.subtitle.board": "프로젝트 보드",
        "header.sharedMode": "요청받은 할 일",
        "header.sharedSubtitle": "공유된 지시 리스트입니다",
        // Header Icons
        "icon.alarm": "알림",
        "icon.received": "받은 일",
        "icon.sent": "보낸 일",
        "icon.share": "공유",
        "icon.theme": "테마",
        "icon.sync": "기기연동",
        "icon.settings": "설정",
        "icon.myTodo": "내 할 일",
        "icon.language": "언어",
        // Push
        "push.turnOff": "푸시 알림 끄기",
        "push.turnOn": "푸시 알림 켜기",
        // SmartInput
        "input.placeholder": "할 일을 입력하세요...",
        "input.add": "+ 추가",
        // TodoCard
        "card.settings": "설정",
        "card.delete": "회수(삭제)",
        "card.complete": "완료",
        "card.overdue": "마감 초과",
        "card.dueIn": "후 마감",
        "card.days": "일",
        "card.hours": "시간",
        "card.minutes": "분",
        "card.checklist": "체크리스트",
        "card.deadline": "마감일",
        "card.location": "위치",
        "card.none": "없음",
        "card.save": "저장",
        "card.cancel": "취소",
        "card.delegateTo": "지시 대상",
        "card.completedBy": "님이 완료",
        // TodoList
        "list.clearCompleted": "완료 항목 정리",
        "list.empty": "할 일이 없습니다. 위에서 추가해보세요!",
        // BottomNav
        "nav.list": "리스트",
        "nav.board": "보드",
        "nav.guide": "사용법",
        // Kanban
        "kanban.todo": "할 일",
        "kanban.progress": "진행 중",
        "kanban.waiting": "대기",
        "kanban.done": "완료",
        // GuideModal
        "guide.title": "📖 사용 가이드",
        "guide.prev": "← 이전",
        "guide.next": "다음 →",
        "guide.finish": "✅ 완료",
        "guide.step1.title": "할 일 입력하기",
        "guide.step1.desc": "상단 입력창에 할 일을 입력하고 [+추가] 버튼을 누르세요.\n\n💡 \"내일 오후 3시까지 보고서 제출\" 처럼 자연스럽게 입력하면, 시스템이 자동으로 마감 시간과 내용을 분리해줍니다.",
        "guide.step1.tip": "한국어 날짜 표현(내일, 모레, 다음주 등)도 인식합니다!",
        "guide.step2.title": "할 일 관리 버튼",
        "guide.step2.desc": "각 할 일 카드를 터치하면 3가지 버튼이 나타납니다:\n\n⚙️ 설정 — 마감일 변경, 체크리스트 추가 등\n🗑 회수(삭제) — 할 일을 삭제\n✅ 완료 — 할 일을 완료 처리",
        "guide.step2.tip": "완료된 할 일은 하단에 모이며, 일괄 삭제할 수 있어요.",
        "guide.step3.title": "🔔 알림 설정",
        "guide.step3.desc": "상단의 종 아이콘을 눌러 알림을 켜주세요.\n\n켜두면 상대방이 할 일을 완료했을 때 소리와 진동으로 즉시 알림을 받습니다.\n\n⚙️ [설정] 버튼에서 소리/진동을 따로 on/off할 수 있습니다.",
        "guide.step3.tip": "알림을 받으려면 브라우저 알림 권한을 '허용'해야 합니다.",
        "guide.step4.title": "📮 받은 일 (수신함)",
        "guide.step4.desc": "다른 사람이 나에게 보낸 할 일 목록을 확인할 수 있습니다.\n\n받은 링크를 열면 할 일 목록이 보이고, [완료] 버튼을 눌러 처리하면 보낸 사람에게 알림이 갑니다.",
        "guide.step4.tip": "닉네임을 설정해두면 누가 완료했는지 상대방이 알 수 있어요.",
        "guide.step5.title": "📤 보낸 일 (지시 현황판)",
        "guide.step5.desc": "내가 다른 사람에게 보낸 할 일의 진행 상황을 한눈에 볼 수 있습니다.\n\n상대방이 공유 링크를 열어보면 '확인' 표시가, 완료하면 '완료' 표시가 됩니다.",
        "guide.step5.tip": "보낸 일 삭제도 여기서 가능합니다.",
        "guide.step6.title": "📤 할 일 공유하기",
        "guide.step6.desc": "[공유] 버튼을 누르면 할 일을 선택하여 공유 링크를 만들 수 있습니다.\n\n📌 사용법:\n1. 공유할 할 일을 체크\n2. [링크 생성] 클릭\n3. 카카오톡이나 문자로 링크 전송\n\n상대방이 링크를 열면 할 일 목록이 보이고, 완료 시 나에게 알림이 옵니다.",
        "guide.step6.tip": "한 번에 여러 개의 할 일을 묶어서 보낼 수 있어요.",
        "guide.step7.title": "📱 공유 받은 사람 사용법",
        "guide.step7.desc": "링크를 받은 사람은:\n\n1. 링크를 열면 할 일 목록이 보입니다\n2. 각 할 일의 [완료] 버튼으로 처리\n3. 보낸 사람에게 자동으로 알림이 갑니다\n\n💡 자기 자신의 할 일을 입력하려면 메인 화면(홈)으로 돌아가서 상단 입력창에 입력하세요.",
        "guide.step7.tip": "공유 화면의 [내 할 일] 버튼으로 메인 화면으로 돌아갈 수 있어요.",
        "guide.step8.title": "📲 앱 설치하기 (PWA)",
        "guide.step8.desc": "📱 아이폰:\nSafari에서 하단 공유 버튼(□↑) → [홈 화면에 추가]\n\n🤖 안드로이드:\nChrome에서 메뉴(⋮) → [홈 화면에 추가] 또는 팝업 안내에서 [설치]\n\n💻 PC (Mac/Windows):\nChrome 주소창 오른쪽의 설치 아이콘(⊕) 클릭",
        "guide.step8.tip": "앱으로 설치하면 풀스크린으로 사용하고, 푸시 알림도 받을 수 있어요!",
        "guide.step9.title": "🔄 기기 간 동기화",
        "guide.step9.desc": "[기기연동] 버튼을 눌러 Google 계정으로 로그인하면, 같은 계정으로 로그인한 모든 기기(PC, 핸드폰)에서 할 일이 실시간으로 동기화됩니다.\n\n✅ PC에서 추가한 할 일이 핸드폰에서도 바로 보입니다\n✅ 핸드폰에서 완료하면 PC에서도 즉시 반영됩니다",
        "guide.step9.tip": "로그인 없이도 공유 링크를 통한 협업은 가능합니다.",
        "guide.step10.title": "🎨 테마 & 칸반 보드",
        "guide.step10.desc": "✨ 테마: 상단의 [테마] 버튼으로 3가지 테마(Pro / Kids / Family)를 선택할 수 있습니다.\n\n📊 칸반 보드: 하단 [보드] 탭을 누르면 할 일을 상태별(할 일 → 진행 중 → 대기 → 완료)로 분류하여 볼 수 있습니다. 드래그해서 상태를 변경하세요.",
        "guide.step10.tip": "테마에 따라 폰트와 색상이 바뀌어 분위기가 달라져요!",
        // Settings Modal
        "settings.title": "앱 설정",
        "settings.nickname": "닉네임",
        "settings.sound": "소리 알림",
        "settings.vibration": "진동 알림",
        "settings.close": "닫기",
        // Share Modal
        "share.title": "할 일 공유",
        "share.select": "공유할 항목 선택",
        "share.generate": "공유 링크 생성",
        "share.copy": "링크 복사",
        "share.copied": "복사됨!",
        "share.close": "닫기",
        // Delegation
        "delegation.title": "지시 현황판",
        "delegation.noItems": "보낸 할 일이 없습니다.",
        "delegation.close": "닫기",
        // Received
        "received.title": "받은 일",
        "received.noItems": "받은 할 일이 없습니다.",
        "received.close": "닫기",
        // Sync
        "sync.title": "기기 동기화",
        "sync.close": "닫기",
        // Theme
        "theme.title": "테마 선택",
        // Nickname
        "nickname.title": "닉네임을 설정해주세요",
        "nickname.placeholder": "닉네임 입력",
        "nickname.confirm": "확인",
        // Notification
        "notification.completed": "완료 알림",
        "notification.completedBy": "님이 할 일을 완료했습니다!",
        "notification.someone": "누군가",
        // TodoCard extras
        "card.doneLabel": "✓ 완료",
        "card.undo": "되돌리기",
        // TodoList / KanbanBoard
        "list.completed": "완료됨",
        "list.clearAll": "모두 지우기",
        "list.confirmClear": "완료된 모든 항목을 영구적으로 삭제하시겠습니까?",
        "kanban.clearTitle": "완료 항목 모두 지우기",
        "kanban.waitingFull": "상대방 완료 대기",
        "kanban.doneFull": "최종 완료",
        // ShareModal
        "modal.taskSettings": "작업 설정",
        "modal.deadline": "마감일",
        "modal.remind": "리마인드",
        "modal.today": "오늘",
        "modal.delete": "삭제",
        "modal.share": "공유",
        "modal.save": "저장",
        "modal.copied": "복사됨",
        "date.year": "년",
        "date.month": "월",
        "date.day": "일",
        "date.hour": "시",
        "date.minute": "분",
        "date.am": "오전",
        "date.pm": "오후",
        "remind.10min": "10분 전",
        "remind.30min": "30분 전",
        "remind.1hour": "1시간 전",
        "remind.3hour": "3시간 전",
        "remind.1day": "1일 전",
        // ShareListModal
        "shareList.title": "📋 리스트 공유",
        "shareList.selectAll": "전체 선택",
        "shareList.inProgress": "진행 중",
        "shareList.done": "완료",
        "shareList.noDeadline": "마감일 없음",
        "shareList.share": "공유하기",
        "shareList.copiedDone": "복사 완료!",
        "shareList.shareTitle": "할 일 리스트",
        "shareList.shareHeader": "📋 할 일 리스트 공유",
        "shareList.total": "총",
        "shareList.items": "건",
        "shareList.active": "진행 중",
        "shareList.linkDesc": "👉 링크에서 모두 확인 및 완료하기:",
        // AppSettingsModal
        "settings.appTitle": "앱 설정",
        "settings.nicknameLabel": "내 닉네임 (알림 표시용)",
        "settings.nicknamePlaceholder": "예: 승근, 홍길동",
        "settings.notifOptions": "알림 상세 옵션",
        "settings.soundNotif": "소리 알림",
        "settings.vibrateNotif": "진동 알림",
        // DeviceSyncModal
        "sync.accountTitle": "기기 동기화 계정",
        "sync.desc": "구글 계정으로 로그인하시면, PC와 모바일 어디서나 작성하신 모든 할 일이 완벽하게 실시간 동기화됩니다.",
        "sync.currentAccount": "현재 로그인된 계정",
        "sync.logout": "로그아웃",
        "sync.loginGoogle": "구글로 시작하기 (동기화)",
        "sync.loginNote": "로그인 없이 생성한 기존 데이터는 로그인 즉시 해당 계정으로 안전하게 귀속됩니다.",
        // NicknameModal
        "welcome.title": "환영합니다!",
        "welcome.desc": "할 일을 완료했을 때 일행에게 전송될",
        "welcome.descBold": "본인의 이름(닉네임)",
        "welcome.descEnd": "을 먼저 입력해주세요.",
        "welcome.placeholder": "예: 홍길동, 아빠, 팀장님",
        "welcome.start": "시작하기",
        // DelegationDashboard
        "delegation.sentStatus": "님의 지시 현황",
        "delegation.sentTitle": "지시 현황판 (보낸 일)",
        "delegation.emptyMsg": "아직 다른 사람에게 전달한 할 일이 없습니다.",
        "delegation.emptyHint": "메인 리스트에서 여러 항목을 체크한 뒤 [공유하기]를 눌러 링크를 전달해보세요.",
        "delegation.pendingLabel": "⏳ 수신 대기중 (미확인)",
        "delegation.progress": "개 완료",
        // ReceivedTasksDashboard
        "received.fromSender": "님이 보낸 일",
        "received.inboxTitle": "수신함 (받은 일)",
        "received.emptyMsg": "아직 다른 사람에게서 받은 할 일이 없습니다.",
        "received.emptyHint": "누군가 공유 링크를 통해 회원님을 담당자로 지정하면 이곳에 나타납니다.",
        // InstallPrompt
        "install.download": "앱 다운로드",
        // Time format
        "time.overdue": "마감 초과",
        "time.soon": "곧 마감",
        "time.minutesLeft": "분 남음",
        "time.hoursMinutesLeft": "시간 {m}분 남음",
        "time.hoursLeft": "시간 남음",
        "time.daysHoursLeft": "일 {h}시간 남음",
        "time.daysLeft": "일 남음",
        // Welcome page
        "page.welcome": "환영합니다 👋",
        "page.welcomeDesc": "홈 화면 앱(또는 새 브라우저) 환경입니다.",
        "page.welcomeAsk": "어떻게 시작할까요?",
        "page.newTodo": "새로운 할일 시작",
        "page.or": "또는",
        "page.joinTitle": "기존 작업실 연결 (동기화 복원)",
        "page.joinDesc": "사파리나 카카오톡 브라우저에서 '복사'한 주소를 붙여넣어 주세요.",
        "page.joinPlaceholder": "예: https://.../?w=...",
        "page.joinBtn": "주소 연결하기",
        "page.invalidUrl": "올바른 작업실 주소(또는 ID)가 아닙니다.",
    },

    en: {
        "header.title": "Your To-Do",
        "header.subtitle.list": "Today's Tasks",
        "header.subtitle.board": "Project Board",
        "header.sharedMode": "Assigned Tasks",
        "header.sharedSubtitle": "Shared task list",
        "icon.alarm": "Alerts",
        "icon.received": "Inbox",
        "icon.sent": "Sent",
        "icon.share": "Share",
        "icon.theme": "Theme",
        "icon.sync": "Sync",
        "icon.settings": "Settings",
        "icon.myTodo": "My Tasks",
        "icon.language": "Lang",
        "push.turnOff": "Turn off push notifications",
        "push.turnOn": "Turn on push notifications",
        "input.placeholder": "Enter a task...",
        "input.add": "+ Add",
        "card.settings": "Settings",
        "card.delete": "Delete",
        "card.complete": "Done",
        "card.overdue": "Overdue",
        "card.dueIn": "due in",
        "card.days": "d",
        "card.hours": "h",
        "card.minutes": "m",
        "card.checklist": "Checklist",
        "card.deadline": "Deadline",
        "card.location": "Location",
        "card.none": "None",
        "card.save": "Save",
        "card.cancel": "Cancel",
        "card.delegateTo": "Assign to",
        "card.completedBy": " completed",
        "list.clearCompleted": "Clear completed",
        "list.empty": "No tasks yet. Add one above!",
        "nav.list": "List",
        "nav.board": "Board",
        "nav.guide": "Guide",
        "kanban.todo": "To Do",
        "kanban.progress": "In Progress",
        "kanban.waiting": "Waiting",
        "kanban.done": "Done",
        "guide.title": "📖 User Guide",
        "guide.prev": "← Prev",
        "guide.next": "Next →",
        "guide.finish": "✅ Done",
        "guide.step1.title": "Adding a Task",
        "guide.step1.desc": "Type your task in the input field and press [+ Add].\n\n💡 Type naturally like \"Submit report by 3pm tomorrow\" and the system will automatically separate the deadline and content.",
        "guide.step1.tip": "Natural date expressions like tomorrow, next week, etc. are recognized!",
        "guide.step2.title": "Task Action Buttons",
        "guide.step2.desc": "Tap a task card to reveal 3 buttons:\n\n⚙️ Settings — Change deadline, add checklist, etc.\n🗑 Delete — Remove the task\n✅ Done — Mark as complete",
        "guide.step2.tip": "Completed tasks collect at the bottom and can be cleared at once.",
        "guide.step3.title": "🔔 Notification Settings",
        "guide.step3.desc": "Tap the bell icon at the top to enable notifications.\n\nWhen enabled, you'll be notified instantly with sound and vibration when someone completes a task.\n\n⚙️ Sound/vibration can be toggled separately in [Settings].",
        "guide.step3.tip": "You must allow browser notification permission to receive alerts.",
        "guide.step4.title": "📮 Inbox (Received Tasks)",
        "guide.step4.desc": "View tasks that others have sent to you.\n\nOpen the shared link to see the task list, and press [Done] to complete them. The sender will be notified automatically.",
        "guide.step4.tip": "Set your nickname so others know who completed the task.",
        "guide.step5.title": "📤 Sent Tasks (Dashboard)",
        "guide.step5.desc": "Track the progress of tasks you've sent to others.\n\nWhen the recipient opens the link, it shows 'Viewed'. When completed, it shows 'Done'.",
        "guide.step5.tip": "You can also delete sent tasks from here.",
        "guide.step6.title": "📤 Sharing Tasks",
        "guide.step6.desc": "Press [Share] to select tasks and create a share link.\n\n📌 How to:\n1. Check the tasks to share\n2. Click [Generate Link]\n3. Send via messenger or text\n\nWhen the recipient opens the link, they can see and complete the tasks.",
        "guide.step6.tip": "You can bundle multiple tasks in a single share link.",
        "guide.step7.title": "📱 For Recipients",
        "guide.step7.desc": "If you received a link:\n\n1. Open the link to see the task list\n2. Press [Done] on each task to complete\n3. The sender is notified automatically\n\n💡 To add your own tasks, go to the home screen and use the input field at the top.",
        "guide.step7.tip": "Use the [My Tasks] button to return to the main screen.",
        "guide.step8.title": "📲 Installing the App (PWA)",
        "guide.step8.desc": "📱 iPhone:\nIn Safari, tap Share (□↑) → [Add to Home Screen]\n\n🤖 Android:\nIn Chrome, tap Menu (⋮) → [Add to Home Screen] or tap [Install] from the popup\n\n💻 PC (Mac/Windows):\nClick the install icon (⊕) in Chrome's address bar",
        "guide.step8.tip": "Installing as an app enables fullscreen mode and push notifications!",
        "guide.step9.title": "🔄 Device Sync",
        "guide.step9.desc": "Press [Sync] and sign in with Google to sync your tasks across all devices (PC, phone) in real-time.\n\n✅ Tasks added on PC appear on your phone instantly\n✅ Tasks completed on phone reflect on PC immediately",
        "guide.step9.tip": "Collaboration via share links works even without signing in.",
        "guide.step10.title": "🎨 Themes & Kanban Board",
        "guide.step10.desc": "✨ Themes: Choose from 3 themes (Pro / Kids / Family) using the [Theme] button.\n\n📊 Kanban Board: Tap the [Board] tab to view tasks by status (To Do → In Progress → Waiting → Done). Drag to change status.",
        "guide.step10.tip": "Each theme changes fonts and colors for a different feel!",
        "settings.title": "App Settings",
        "settings.nickname": "Nickname",
        "settings.sound": "Sound Notification",
        "settings.vibration": "Vibration",
        "settings.close": "Close",
        "share.title": "Share Tasks",
        "share.select": "Select items to share",
        "share.generate": "Generate Share Link",
        "share.copy": "Copy Link",
        "share.copied": "Copied!",
        "share.close": "Close",
        "delegation.title": "Sent Tasks Dashboard",
        "delegation.noItems": "No sent tasks.",
        "delegation.close": "Close",
        "received.title": "Inbox",
        "received.noItems": "No received tasks.",
        "received.close": "Close",
        "sync.title": "Device Sync",
        "sync.close": "Close",
        "theme.title": "Select Theme",
        "nickname.title": "Set your nickname",
        "nickname.placeholder": "Enter nickname",
        "nickname.confirm": "Confirm",
        "notification.completed": "Task Completed",
        "notification.completedBy": " completed a task!",
        "notification.someone": "Someone",
        "card.doneLabel": "✓ Done",
        "card.undo": "Undo",
        "list.completed": "Completed",
        "list.clearAll": "Clear all",
        "list.confirmClear": "Permanently delete all completed items?",
        "kanban.clearTitle": "Clear all completed",
        "kanban.waitingFull": "Waiting for completion",
        "kanban.doneFull": "Completed",
        "modal.taskSettings": "Task Settings",
        "modal.deadline": "Deadline",
        "modal.remind": "Reminder",
        "modal.today": "Today",
        "modal.delete": "Delete",
        "modal.share": "Share",
        "modal.save": "Save",
        "modal.copied": "Copied",
        "date.year": "",
        "date.month": "/",
        "date.day": "",
        "date.hour": ":",
        "date.minute": "",
        "date.am": "AM",
        "date.pm": "PM",
        "remind.10min": "10 min before",
        "remind.30min": "30 min before",
        "remind.1hour": "1 hour before",
        "remind.3hour": "3 hours before",
        "remind.1day": "1 day before",
        "shareList.title": "📋 Share List",
        "shareList.selectAll": "Select all",
        "shareList.inProgress": "In Progress",
        "shareList.done": "Done",
        "shareList.noDeadline": "No deadline",
        "shareList.share": "Share",
        "shareList.copiedDone": "Copied!",
        "shareList.shareTitle": "Task List",
        "shareList.shareHeader": "📋 Task List Share",
        "shareList.total": "Total",
        "shareList.items": "items",
        "shareList.active": "active",
        "shareList.linkDesc": "👉 View and complete all tasks here:",
        "settings.appTitle": "App Settings",
        "settings.nicknameLabel": "Nickname (for notifications)",
        "settings.nicknamePlaceholder": "e.g. John, Dad, Boss",
        "settings.notifOptions": "Notification Options",
        "settings.soundNotif": "Sound",
        "settings.vibrateNotif": "Vibration",
        "sync.accountTitle": "Device Sync Account",
        "sync.desc": "Sign in with Google to sync all your tasks across PC and mobile in real-time.",
        "sync.currentAccount": "Currently signed in",
        "sync.logout": "Sign out",
        "sync.loginGoogle": "Sign in with Google (Sync)",
        "sync.loginNote": "Data created without login will be safely linked to your account upon sign-in.",
        "welcome.title": "Welcome!",
        "welcome.desc": "When a task is completed, your",
        "welcome.descBold": "name (nickname)",
        "welcome.descEnd": " will be shown to others.",
        "welcome.placeholder": "e.g. John, Dad, Boss",
        "welcome.start": "Get Started",
        "delegation.sentStatus": "'s task status",
        "delegation.sentTitle": "Sent Tasks Dashboard",
        "delegation.emptyMsg": "No tasks delegated to others yet.",
        "delegation.emptyHint": "Select items from the main list and press [Share] to send a link.",
        "delegation.pendingLabel": "⏳ Pending (unconfirmed)",
        "delegation.progress": " completed",
        "received.fromSender": "'s tasks",
        "received.inboxTitle": "Inbox (Received)",
        "received.emptyMsg": "No tasks received from others yet.",
        "received.emptyHint": "Tasks will appear here when someone assigns you via a share link.",
        "install.download": "Install App",
        "time.overdue": "Overdue",
        "time.soon": "Due soon",
        "time.minutesLeft": "m left",
        "time.hoursMinutesLeft": "h {m}m left",
        "time.hoursLeft": "h left",
        "time.daysHoursLeft": "d {h}h left",
        "time.daysLeft": "d left",
        "page.welcome": "Welcome 👋",
        "page.welcomeDesc": "Home screen app (or new browser) detected.",
        "page.welcomeAsk": "How would you like to start?",
        "page.newTodo": "Start new workspace",
        "page.or": "or",
        "page.joinTitle": "Join existing workspace (restore sync)",
        "page.joinDesc": "Paste the workspace URL you copied from another browser.",
        "page.joinPlaceholder": "e.g. https://.../?w=...",
        "page.joinBtn": "Connect",
        "page.invalidUrl": "Invalid workspace URL or ID.",
    },

    ja: {
        "header.title": "Your To-Do",
        "header.subtitle.list": "今日のタスク",
        "header.subtitle.board": "プロジェクトボード",
        "header.sharedMode": "依頼されたタスク",
        "header.sharedSubtitle": "共有タスクリスト",
        "icon.alarm": "通知",
        "icon.received": "受信",
        "icon.sent": "送信",
        "icon.share": "共有",
        "icon.theme": "テーマ",
        "icon.sync": "同期",
        "icon.settings": "設定",
        "icon.myTodo": "マイタスク",
        "icon.language": "言語",
        "push.turnOff": "プッシュ通知をオフ",
        "push.turnOn": "プッシュ通知をオン",
        "input.placeholder": "タスクを入力...",
        "input.add": "+ 追加",
        "card.settings": "設定",
        "card.delete": "削除",
        "card.complete": "完了",
        "card.overdue": "期限超過",
        "card.dueIn": "後に期限",
        "card.days": "日",
        "card.hours": "時間",
        "card.minutes": "分",
        "card.checklist": "チェックリスト",
        "card.deadline": "期限",
        "card.location": "場所",
        "card.none": "なし",
        "card.save": "保存",
        "card.cancel": "キャンセル",
        "card.delegateTo": "担当者",
        "card.completedBy": "が完了",
        "list.clearCompleted": "完了項目を整理",
        "list.empty": "タスクがありません。上から追加してください！",
        "nav.list": "リスト",
        "nav.board": "ボード",
        "nav.guide": "使い方",
        "kanban.todo": "未着手",
        "kanban.progress": "進行中",
        "kanban.waiting": "待機",
        "kanban.done": "完了",
        "guide.title": "📖 使い方ガイド",
        "guide.prev": "← 前へ",
        "guide.next": "次へ →",
        "guide.finish": "✅ 完了",
        "guide.step1.title": "タスクの追加",
        "guide.step1.desc": "上部の入力欄にタスクを入力し、[+追加]ボタンを押してください。\n\n💡「明日午後3時までに報告書提出」のように自然に入力すると、システムが自動で期限と内容を分離します。",
        "guide.step1.tip": "日本語の日時表現（明日、来週など）も認識します！",
        "guide.step2.title": "タスク管理ボタン",
        "guide.step2.desc": "タスクカードをタップすると3つのボタンが表示されます：\n\n⚙️ 設定 — 期限変更、チェックリスト追加など\n🗑 削除 — タスクを削除\n✅ 完了 — タスクを完了にする",
        "guide.step2.tip": "完了したタスクは下に集まり、一括削除できます。",
        "guide.step3.title": "🔔 通知設定",
        "guide.step3.desc": "上部のベルアイコンをタップして通知を有効にしてください。\n\n有効にすると、相手がタスクを完了した時に音と振動で即座に通知されます。\n\n⚙️ [設定]で音・振動を個別にon/offできます。",
        "guide.step3.tip": "ブラウザの通知許可を「許可」にする必要があります。",
        "guide.step4.title": "📮 受信ボックス",
        "guide.step4.desc": "他の人から送られたタスクリストを確認できます。\n\n共有リンクを開くとタスクリストが表示され、[完了]ボタンで処理すると送信者に通知されます。",
        "guide.step4.tip": "ニックネームを設定すると、誰が完了したか相手に分かります。",
        "guide.step5.title": "📤 送信済みタスク",
        "guide.step5.desc": "他の人に送ったタスクの進捗を一目で確認できます。\n\n相手が共有リンクを開くと「確認済み」、完了すると「完了」と表示されます。",
        "guide.step5.tip": "送信済みタスクの削除もここでできます。",
        "guide.step6.title": "📤 タスクを共有",
        "guide.step6.desc": "[共有]ボタンでタスクを選択して共有リンクを作成できます。\n\n📌 使い方：\n1. 共有するタスクをチェック\n2. [リンク作成]をクリック\n3. メッセンジャーやSMSでリンクを送信\n\n相手がリンクを開くと、タスクリストが表示されます。",
        "guide.step6.tip": "複数のタスクをまとめて送れます。",
        "guide.step7.title": "📱 受信者の使い方",
        "guide.step7.desc": "リンクを受け取った人は：\n\n1. リンクを開くとタスクリストが表示されます\n2. 各タスクの[完了]ボタンで処理\n3. 送信者に自動で通知されます\n\n💡 自分のタスクを追加するには、ホーム画面に戻って上部の入力欄を使ってください。",
        "guide.step7.tip": "[マイタスク]ボタンでメイン画面に戻れます。",
        "guide.step8.title": "📲 アプリインストール (PWA)",
        "guide.step8.desc": "📱 iPhone：\nSafariで共有ボタン(□↑) → [ホーム画面に追加]\n\n🤖 Android：\nChromeでメニュー(⋮) → [ホーム画面に追加]またはポップアップの[インストール]\n\n💻 PC (Mac/Windows)：\nChromeアドレスバー右のインストールアイコン(⊕)をクリック",
        "guide.step8.tip": "アプリとしてインストールすると、フルスクリーンで使え、プッシュ通知も受け取れます！",
        "guide.step9.title": "🔄 デバイス間同期",
        "guide.step9.desc": "[同期]ボタンからGoogleアカウントでログインすると、同じアカウントの全デバイス（PC、スマホ）でタスクがリアルタイム同期されます。\n\n✅ PCで追加したタスクがスマホにも即反映\n✅ スマホで完了するとPCにも即反映",
        "guide.step9.tip": "ログインなしでも共有リンクでのコラボは可能です。",
        "guide.step10.title": "🎨 テーマ＆カンバンボード",
        "guide.step10.desc": "✨ テーマ：[テーマ]ボタンから3種類（Pro / Kids / Family）を選べます。\n\n📊 カンバンボード：[ボード]タブでタスクをステータス別（未着手→進行中→待機→完了）に表示。ドラッグで変更できます。",
        "guide.step10.tip": "テーマによってフォントと色が変わり、雰囲気が変わります！",
        "settings.title": "アプリ設定",
        "settings.nickname": "ニックネーム",
        "settings.sound": "サウンド通知",
        "settings.vibration": "バイブ通知",
        "settings.close": "閉じる",
        "share.title": "タスク共有",
        "share.select": "共有する項目を選択",
        "share.generate": "共有リンク作成",
        "share.copy": "リンクをコピー",
        "share.copied": "コピー済み！",
        "share.close": "閉じる",
        "delegation.title": "送信済みダッシュボード",
        "delegation.noItems": "送信済みのタスクはありません。",
        "delegation.close": "閉じる",
        "received.title": "受信ボックス",
        "received.noItems": "受信したタスクはありません。",
        "received.close": "閉じる",
        "sync.title": "デバイス同期",
        "sync.close": "閉じる",
        "theme.title": "テーマ選択",
        "nickname.title": "ニックネームを設定してください",
        "nickname.placeholder": "ニックネーム入力",
        "nickname.confirm": "確認",
        "notification.completed": "タスク完了通知",
        "notification.completedBy": "がタスクを完了しました！",
        "notification.someone": "誰か",
        "card.doneLabel": "✓ 完了",
        "card.undo": "元に戻す",
        "list.completed": "完了済み",
        "list.clearAll": "全て削除",
        "list.confirmClear": "完了した全ての項目を永久に削除しますか？",
        "kanban.clearTitle": "完了項目を全て削除",
        "kanban.waitingFull": "完了待ち",
        "kanban.doneFull": "最終完了",
        "modal.taskSettings": "タスク設定",
        "modal.deadline": "期限",
        "modal.remind": "リマインド",
        "modal.today": "今日",
        "modal.delete": "削除",
        "modal.share": "共有",
        "modal.save": "保存",
        "modal.copied": "コピー済み",
        "date.year": "年",
        "date.month": "月",
        "date.day": "日",
        "date.hour": "時",
        "date.minute": "分",
        "date.am": "午前",
        "date.pm": "午後",
        "remind.10min": "10分前",
        "remind.30min": "30分前",
        "remind.1hour": "1時間前",
        "remind.3hour": "3時間前",
        "remind.1day": "1日前",
        "shareList.title": "📋 リスト共有",
        "shareList.selectAll": "全選択",
        "shareList.inProgress": "進行中",
        "shareList.done": "完了",
        "shareList.noDeadline": "期限なし",
        "shareList.share": "共有する",
        "shareList.copiedDone": "コピー完了！",
        "shareList.shareTitle": "タスクリスト",
        "shareList.shareHeader": "📋 タスクリスト共有",
        "shareList.total": "合計",
        "shareList.items": "件",
        "shareList.active": "進行中",
        "shareList.linkDesc": "👉 リンクで確認・完了:",
        "settings.appTitle": "アプリ設定",
        "settings.nicknameLabel": "ニックネーム（通知表示用）",
        "settings.nicknamePlaceholder": "例：太郎、パパ",
        "settings.notifOptions": "通知の詳細設定",
        "settings.soundNotif": "サウンド通知",
        "settings.vibrateNotif": "バイブ通知",
        "sync.accountTitle": "デバイス同期アカウント",
        "sync.desc": "Googleアカウントでログインすると、PCとモバイルで全てのタスクがリアルタイム同期されます。",
        "sync.currentAccount": "現在ログイン中",
        "sync.logout": "ログアウト",
        "sync.loginGoogle": "Googleで開始（同期）",
        "sync.loginNote": "ログインなしで作成したデータは、ログイン後にアカウントに安全に紐付けられます。",
        "welcome.title": "ようこそ！",
        "welcome.desc": "タスク完了時に仲間に送信される",
        "welcome.descBold": "あなたの名前（ニックネーム）",
        "welcome.descEnd": "を入力してください。",
        "welcome.placeholder": "例：太郎、パパ、チーム長",
        "welcome.start": "始める",
        "delegation.sentStatus": "さんのタスク状況",
        "delegation.sentTitle": "送信済みダッシュボード",
        "delegation.emptyMsg": "まだ他の人に送ったタスクはありません。",
        "delegation.emptyHint": "メインリストで項目を選択し、[共有]からリンクを送信してください。",
        "delegation.pendingLabel": "⏳ 受信待ち（未確認）",
        "delegation.progress": "件完了",
        "received.fromSender": "さんからのタスク",
        "received.inboxTitle": "受信ボックス",
        "received.emptyMsg": "まだ他の人からのタスクはありません。",
        "received.emptyHint": "共有リンクで担当者に指定されると、ここに表示されます。",
        "install.download": "アプリダウンロード",
        "time.overdue": "期限超過",
        "time.soon": "まもなく締切",
        "time.minutesLeft": "分残り",
        "time.hoursMinutesLeft": "時間{m}分残り",
        "time.hoursLeft": "時間残り",
        "time.daysHoursLeft": "日{h}時間残り",
        "time.daysLeft": "日残り",
        "page.welcome": "ようこそ 👋",
        "page.welcomeDesc": "ホーム画面アプリ（または新しいブラウザ）です。",
        "page.welcomeAsk": "どう始めますか？",
        "page.newTodo": "新しいワークスペースを作成",
        "page.or": "または",
        "page.joinTitle": "既存のワークスペースに接続（同期復元）",
        "page.joinDesc": "他のブラウザからコピーしたURLを貼り付けてください。",
        "page.joinPlaceholder": "例: https://.../?w=...",
        "page.joinBtn": "接続する",
        "page.invalidUrl": "無効なワークスペースURLまたはIDです。",
    },

    es: {
        "header.title": "Your To-Do",
        "header.subtitle.list": "Tareas de hoy",
        "header.subtitle.board": "Tablero de proyecto",
        "header.sharedMode": "Tareas asignadas",
        "header.sharedSubtitle": "Lista de tareas compartida",
        "icon.alarm": "Alertas",
        "icon.received": "Recibido",
        "icon.sent": "Enviado",
        "icon.share": "Compartir",
        "icon.theme": "Tema",
        "icon.sync": "Sincr.",
        "icon.settings": "Config.",
        "icon.myTodo": "Mis tareas",
        "icon.language": "Idioma",
        "push.turnOff": "Desactivar notificaciones",
        "push.turnOn": "Activar notificaciones",
        "input.placeholder": "Escribe una tarea...",
        "input.add": "+ Agregar",
        "card.settings": "Config.",
        "card.delete": "Eliminar",
        "card.complete": "Hecho",
        "card.overdue": "Vencida",
        "card.dueIn": "vence en",
        "card.days": "d",
        "card.hours": "h",
        "card.minutes": "m",
        "card.checklist": "Lista de verificación",
        "card.deadline": "Fecha límite",
        "card.location": "Ubicación",
        "card.none": "Ninguno",
        "card.save": "Guardar",
        "card.cancel": "Cancelar",
        "card.delegateTo": "Asignar a",
        "card.completedBy": " completó",
        "list.clearCompleted": "Limpiar completadas",
        "list.empty": "No hay tareas. ¡Agrega una arriba!",
        "nav.list": "Lista",
        "nav.board": "Tablero",
        "nav.guide": "Guía",
        "kanban.todo": "Por hacer",
        "kanban.progress": "En progreso",
        "kanban.waiting": "Esperando",
        "kanban.done": "Hecho",
        "guide.title": "📖 Guía de uso",
        "guide.prev": "← Anterior",
        "guide.next": "Siguiente →",
        "guide.finish": "✅ Listo",
        "guide.step1.title": "Agregar una tarea",
        "guide.step1.desc": "Escribe tu tarea en el campo de entrada y presiona [+ Agregar].\n\n💡 Escribe naturalmente como \"Entregar informe mañana a las 3pm\" y el sistema separará automáticamente la fecha límite del contenido.",
        "guide.step1.tip": "¡Se reconocen expresiones de fecha como mañana, la próxima semana, etc.!",
        "guide.step2.title": "Botones de acción",
        "guide.step2.desc": "Toca una tarjeta de tarea para ver 3 botones:\n\n⚙️ Config. — Cambiar fecha límite, agregar checklist\n🗑 Eliminar — Borrar la tarea\n✅ Hecho — Marcar como completada",
        "guide.step2.tip": "Las tareas completadas se agrupan abajo y se pueden eliminar juntas.",
        "guide.step3.title": "🔔 Configurar notificaciones",
        "guide.step3.desc": "Toca el icono de campana arriba para activar las notificaciones.\n\nCuando está activado, recibirás sonido y vibración cuando alguien complete una tarea.\n\n⚙️ Puedes activar/desactivar sonido y vibración por separado en [Config.].",
        "guide.step3.tip": "Debes permitir las notificaciones del navegador para recibirlas.",
        "guide.step4.title": "📮 Bandeja de entrada",
        "guide.step4.desc": "Ve las tareas que otros te han enviado.\n\nAbre el enlace compartido para ver la lista, y presiona [Hecho] para completarlas. El remitente será notificado.",
        "guide.step4.tip": "Configura tu apodo para que otros sepan quién completó la tarea.",
        "guide.step5.title": "📤 Tareas enviadas",
        "guide.step5.desc": "Rastrea el progreso de las tareas que has enviado.\n\nCuando el destinatario abre el enlace, muestra 'Visto'. Cuando completa, muestra 'Hecho'.",
        "guide.step5.tip": "También puedes eliminar tareas enviadas desde aquí.",
        "guide.step6.title": "📤 Compartir tareas",
        "guide.step6.desc": "Presiona [Compartir] para seleccionar tareas y crear un enlace.\n\n📌 Cómo:\n1. Marca las tareas a compartir\n2. Clic en [Generar enlace]\n3. Envía por mensajero o SMS\n\nEl destinatario puede ver y completar las tareas desde el enlace.",
        "guide.step6.tip": "Puedes agrupar varias tareas en un solo enlace.",
        "guide.step7.title": "📱 Para destinatarios",
        "guide.step7.desc": "Si recibiste un enlace:\n\n1. Ábrelo para ver la lista de tareas\n2. Presiona [Hecho] en cada tarea\n3. El remitente recibe notificación automática\n\n💡 Para agregar tus propias tareas, ve a la pantalla principal.",
        "guide.step7.tip": "Usa [Mis tareas] para volver a la pantalla principal.",
        "guide.step8.title": "📲 Instalar la app (PWA)",
        "guide.step8.desc": "📱 iPhone:\nEn Safari, toca Compartir (□↑) → [Agregar a pantalla de inicio]\n\n🤖 Android:\nEn Chrome, toca Menú (⋮) → [Agregar a pantalla de inicio]\n\n💻 PC (Mac/Windows):\nClic en el icono de instalación (⊕) en la barra de Chrome",
        "guide.step8.tip": "¡Al instalarla como app, funciona en pantalla completa con notificaciones push!",
        "guide.step9.title": "🔄 Sincronización",
        "guide.step9.desc": "Presiona [Sincr.] e inicia sesión con Google para sincronizar tareas en todos tus dispositivos en tiempo real.\n\n✅ Tareas agregadas en PC aparecen en tu teléfono al instante\n✅ Tareas completadas en teléfono se reflejan en PC inmediatamente",
        "guide.step9.tip": "La colaboración por enlaces funciona sin iniciar sesión.",
        "guide.step10.title": "🎨 Temas y Tablero Kanban",
        "guide.step10.desc": "✨ Temas: Elige entre 3 temas (Pro / Kids / Family) con el botón [Tema].\n\n📊 Kanban: Toca [Tablero] para ver tareas por estado (Por hacer → En progreso → Esperando → Hecho). Arrastra para cambiar estado.",
        "guide.step10.tip": "¡Cada tema cambia fuentes y colores para un estilo diferente!",
        "settings.title": "Configuración",
        "settings.nickname": "Apodo",
        "settings.sound": "Sonido",
        "settings.vibration": "Vibración",
        "settings.close": "Cerrar",
        "share.title": "Compartir tareas",
        "share.select": "Seleccionar tareas",
        "share.generate": "Generar enlace",
        "share.copy": "Copiar enlace",
        "share.copied": "¡Copiado!",
        "share.close": "Cerrar",
        "delegation.title": "Tareas enviadas",
        "delegation.noItems": "No hay tareas enviadas.",
        "delegation.close": "Cerrar",
        "received.title": "Bandeja de entrada",
        "received.noItems": "No hay tareas recibidas.",
        "received.close": "Cerrar",
        "sync.title": "Sincronización",
        "sync.close": "Cerrar",
        "theme.title": "Seleccionar tema",
        "nickname.title": "Configura tu apodo",
        "nickname.placeholder": "Escribe un apodo",
        "nickname.confirm": "Confirmar",
        "notification.completed": "Tarea completada",
        "notification.completedBy": " completó una tarea!",
        "notification.someone": "Alguien",
        "card.doneLabel": "✓ Hecho",
        "card.undo": "Deshacer",
        "list.completed": "Completadas",
        "list.clearAll": "Limpiar todo",
        "list.confirmClear": "¿Eliminar permanentemente todos los elementos completados?",
        "kanban.clearTitle": "Limpiar todos los completados",
        "kanban.waitingFull": "Esperando finalización",
        "kanban.doneFull": "Completado",
        "modal.taskSettings": "Configuración de tarea",
        "modal.deadline": "Fecha límite",
        "modal.remind": "Recordatorio",
        "modal.today": "Hoy",
        "modal.delete": "Eliminar",
        "modal.share": "Compartir",
        "modal.save": "Guardar",
        "modal.copied": "Copiado",
        "date.year": "",
        "date.month": "/",
        "date.day": "",
        "date.hour": ":",
        "date.minute": "",
        "date.am": "AM",
        "date.pm": "PM",
        "remind.10min": "10 min antes",
        "remind.30min": "30 min antes",
        "remind.1hour": "1 hora antes",
        "remind.3hour": "3 horas antes",
        "remind.1day": "1 día antes",
        "shareList.title": "📋 Compartir lista",
        "shareList.selectAll": "Seleccionar todo",
        "shareList.inProgress": "En progreso",
        "shareList.done": "Hecho",
        "shareList.noDeadline": "Sin fecha límite",
        "shareList.share": "Compartir",
        "shareList.copiedDone": "¡Copiado!",
        "shareList.shareTitle": "Lista de tareas",
        "shareList.shareHeader": "📋 Lista de tareas compartida",
        "shareList.total": "Total",
        "shareList.items": "elementos",
        "shareList.active": "activas",
        "shareList.linkDesc": "👉 Ver y completar todas las tareas aquí:",
        "settings.appTitle": "Configuración",
        "settings.nicknameLabel": "Apodo (para notificaciones)",
        "settings.nicknamePlaceholder": "Ej: Juan, Papá, Jefe",
        "settings.notifOptions": "Opciones de notificación",
        "settings.soundNotif": "Sonido",
        "settings.vibrateNotif": "Vibración",
        "sync.accountTitle": "Cuenta de sincronización",
        "sync.desc": "Inicia sesión con Google para sincronizar todas tus tareas entre PC y móvil en tiempo real.",
        "sync.currentAccount": "Cuenta actual",
        "sync.logout": "Cerrar sesión",
        "sync.loginGoogle": "Iniciar con Google (Sincr.)",
        "sync.loginNote": "Los datos creados sin sesión se vincularán a tu cuenta al iniciar sesión.",
        "welcome.title": "¡Bienvenido!",
        "welcome.desc": "Cuando se complete una tarea, tu",
        "welcome.descBold": "nombre (apodo)",
        "welcome.descEnd": " se mostrará a otros.",
        "welcome.placeholder": "Ej: Juan, Papá, Jefe",
        "welcome.start": "Comenzar",
        "delegation.sentStatus": " - Estado de tareas",
        "delegation.sentTitle": "Panel de tareas enviadas",
        "delegation.emptyMsg": "No has enviado tareas a nadie aún.",
        "delegation.emptyHint": "Selecciona elementos y presiona [Compartir] para enviar un enlace.",
        "delegation.pendingLabel": "⏳ Pendiente (sin confirmar)",
        "delegation.progress": " completadas",
        "received.fromSender": " - Tareas recibidas",
        "received.inboxTitle": "Bandeja de entrada",
        "received.emptyMsg": "Aún no has recibido tareas.",
        "received.emptyHint": "Las tareas aparecerán cuando alguien te asigne mediante un enlace.",
        "install.download": "Instalar app",
        "time.overdue": "Vencida",
        "time.soon": "Por vencer",
        "time.minutesLeft": "min restantes",
        "time.hoursMinutesLeft": "h {m}min restantes",
        "time.hoursLeft": "h restantes",
        "time.daysHoursLeft": "d {h}h restantes",
        "time.daysLeft": "d restantes",
        "page.welcome": "Bienvenido 👋",
        "page.welcomeDesc": "App de pantalla de inicio (o nuevo navegador).",
        "page.welcomeAsk": "¿Cómo quieres empezar?",
        "page.newTodo": "Nuevo espacio de trabajo",
        "page.or": "o",
        "page.joinTitle": "Conectar espacio existente",
        "page.joinDesc": "Pega la URL del espacio de trabajo copiada de otro navegador.",
        "page.joinPlaceholder": "Ej: https://.../?w=...",
        "page.joinBtn": "Conectar",
        "page.invalidUrl": "URL o ID de espacio no válido.",
    },

    zh: {
        "header.title": "Your To-Do",
        "header.subtitle.list": "今日任务",
        "header.subtitle.board": "项目看板",
        "header.sharedMode": "已分配的任务",
        "header.sharedSubtitle": "共享任务列表",
        "icon.alarm": "通知",
        "icon.received": "收件箱",
        "icon.sent": "已发送",
        "icon.share": "分享",
        "icon.theme": "主题",
        "icon.sync": "同步",
        "icon.settings": "设置",
        "icon.myTodo": "我的任务",
        "icon.language": "语言",
        "push.turnOff": "关闭推送通知",
        "push.turnOn": "开启推送通知",
        "input.placeholder": "输入任务...",
        "input.add": "+ 添加",
        "card.settings": "设置",
        "card.delete": "删除",
        "card.complete": "完成",
        "card.overdue": "已过期",
        "card.dueIn": "后截止",
        "card.days": "天",
        "card.hours": "小时",
        "card.minutes": "分钟",
        "card.checklist": "清单",
        "card.deadline": "截止日期",
        "card.location": "位置",
        "card.none": "无",
        "card.save": "保存",
        "card.cancel": "取消",
        "card.delegateTo": "分配给",
        "card.completedBy": "完成了任务",
        "list.clearCompleted": "清除已完成",
        "list.empty": "还没有任务，在上方添加一个吧！",
        "nav.list": "列表",
        "nav.board": "看板",
        "nav.guide": "指南",
        "kanban.todo": "待办",
        "kanban.progress": "进行中",
        "kanban.waiting": "等待中",
        "kanban.done": "已完成",
        "guide.title": "📖 使用指南",
        "guide.prev": "← 上一步",
        "guide.next": "下一步 →",
        "guide.finish": "✅ 完成",
        "guide.step1.title": "添加任务",
        "guide.step1.desc": "在上方输入框中输入任务，然后点击[+添加]按钮。\n\n💡 自然地输入如\"明天下午3点前提交报告\"，系统会自动分离截止时间和内容。",
        "guide.step1.tip": "支持识别中文日期表达（明天、下周等）！",
        "guide.step2.title": "任务操作按钮",
        "guide.step2.desc": "点击任务卡片会显示3个按钮：\n\n⚙️ 设置 — 修改截止日期、添加清单等\n🗑 删除 — 删除任务\n✅ 完成 — 标记为已完成",
        "guide.step2.tip": "已完成的任务会集中在底部，可以一键清除。",
        "guide.step3.title": "🔔 通知设置",
        "guide.step3.desc": "点击顶部的铃铛图标开启通知。\n\n开启后，当有人完成任务时，您会立即收到声音和振动提醒。\n\n⚙️ 可以在[设置]中单独开关声音和振动。",
        "guide.step3.tip": "需要在浏览器中允许通知权限才能接收提醒。",
        "guide.step4.title": "📮 收件箱（收到的任务）",
        "guide.step4.desc": "查看他人发给你的任务列表。\n\n打开共享链接查看任务列表，点击[完成]按钮处理后，发送者会收到通知。",
        "guide.step4.tip": "设置昵称后，对方就能知道是谁完成了任务。",
        "guide.step5.title": "📤 已发送的任务",
        "guide.step5.desc": "一目了然地查看你发给他人的任务进度。\n\n对方打开共享链接后显示\"已查看\"，完成后显示\"已完成\"。",
        "guide.step5.tip": "也可以在这里删除已发送的任务。",
        "guide.step6.title": "📤 分享任务",
        "guide.step6.desc": "点击[分享]按钮选择任务并生成分享链接。\n\n📌 使用方法：\n1. 勾选要分享的任务\n2. 点击[生成链接]\n3. 通过微信或短信发送链接\n\n对方打开链接即可查看并完成任务。",
        "guide.step6.tip": "可以将多个任务打包在一个链接中发送。",
        "guide.step7.title": "📱 接收者使用方法",
        "guide.step7.desc": "如果你收到了链接：\n\n1. 打开链接查看任务列表\n2. 点击每个任务的[完成]按钮\n3. 发送者会自动收到通知\n\n💡 要添加自己的任务，请返回主页面使用顶部输入框。",
        "guide.step7.tip": "点击[我的任务]按钮返回主页面。",
        "guide.step8.title": "📲 安装应用 (PWA)",
        "guide.step8.desc": "📱 iPhone：\n在Safari中点击分享按钮(□↑) → [添加到主屏幕]\n\n🤖 安卓：\n在Chrome中点击菜单(⋮) → [添加到主屏幕]或点击弹窗中的[安装]\n\n💻 电脑 (Mac/Windows)：\n点击Chrome地址栏右侧的安装图标(⊕)",
        "guide.step8.tip": "安装为应用后可以全屏使用，还能接收推送通知！",
        "guide.step9.title": "🔄 设备同步",
        "guide.step9.desc": "点击[同步]并用Google账号登录，所有设备（电脑、手机）上的任务将实时同步。\n\n✅ 电脑上添加的任务会立即出现在手机上\n✅ 手机上完成的任务会立即反映在电脑上",
        "guide.step9.tip": "不登录也可以通过分享链接进行协作。",
        "guide.step10.title": "🎨 主题和看板",
        "guide.step10.desc": "✨ 主题：通过[主题]按钮选择3种主题（Pro / Kids / Family）。\n\n📊 看板：点击[看板]标签按状态查看任务（待办→进行中→等待中→已完成）。拖动可更改状态。",
        "guide.step10.tip": "每个主题都有不同的字体和颜色风格！",
        "settings.title": "应用设置",
        "settings.nickname": "昵称",
        "settings.sound": "声音通知",
        "settings.vibration": "振动通知",
        "settings.close": "关闭",
        "share.title": "分享任务",
        "share.select": "选择要分享的项目",
        "share.generate": "生成分享链接",
        "share.copy": "复制链接",
        "share.copied": "已复制！",
        "share.close": "关闭",
        "delegation.title": "已发送任务面板",
        "delegation.noItems": "没有已发送的任务。",
        "delegation.close": "关闭",
        "received.title": "收件箱",
        "received.noItems": "没有收到的任务。",
        "received.close": "关闭",
        "sync.title": "设备同步",
        "sync.close": "关闭",
        "theme.title": "选择主题",
        "nickname.title": "请设置你的昵称",
        "nickname.placeholder": "输入昵称",
        "nickname.confirm": "确认",
        "notification.completed": "任务完成通知",
        "notification.completedBy": "完成了一个任务！",
        "notification.someone": "有人",
        "card.doneLabel": "✓ 完成",
        "card.undo": "撤销",
        "list.completed": "已完成",
        "list.clearAll": "全部清除",
        "list.confirmClear": "永久删除所有已完成的项目吗？",
        "kanban.clearTitle": "清除所有已完成项",
        "kanban.waitingFull": "等待完成",
        "kanban.doneFull": "最终完成",
        "modal.taskSettings": "任务设置",
        "modal.deadline": "截止日期",
        "modal.remind": "提醒",
        "modal.today": "今天",
        "modal.delete": "删除",
        "modal.share": "分享",
        "modal.save": "保存",
        "modal.copied": "已复制",
        "date.year": "年",
        "date.month": "月",
        "date.day": "日",
        "date.hour": "时",
        "date.minute": "分",
        "date.am": "上午",
        "date.pm": "下午",
        "remind.10min": "10分钟前",
        "remind.30min": "30分钟前",
        "remind.1hour": "1小时前",
        "remind.3hour": "3小时前",
        "remind.1day": "1天前",
        "shareList.title": "📋 分享列表",
        "shareList.selectAll": "全选",
        "shareList.inProgress": "进行中",
        "shareList.done": "已完成",
        "shareList.noDeadline": "无截止日期",
        "shareList.share": "分享",
        "shareList.copiedDone": "已复制！",
        "shareList.shareTitle": "任务列表",
        "shareList.shareHeader": "📋 任务列表分享",
        "shareList.total": "共",
        "shareList.items": "项",
        "shareList.active": "进行中",
        "shareList.linkDesc": "👉 在链接中查看并完成所有任务:",
        "settings.appTitle": "应用设置",
        "settings.nicknameLabel": "昵称（通知显示用）",
        "settings.nicknamePlaceholder": "例：小明、爸爸",
        "settings.notifOptions": "通知详细选项",
        "settings.soundNotif": "声音通知",
        "settings.vibrateNotif": "振动通知",
        "sync.accountTitle": "设备同步账户",
        "sync.desc": "使用Google账号登录后，您的所有任务将在PC和手机之间实时同步。",
        "sync.currentAccount": "当前登录账户",
        "sync.logout": "退出登录",
        "sync.loginGoogle": "使用Google登录（同步）",
        "sync.loginNote": "未登录时创建的数据将在登录后安全地关联到您的账户。",
        "welcome.title": "欢迎！",
        "welcome.desc": "完成任务时，您的",
        "welcome.descBold": "姓名（昵称）",
        "welcome.descEnd": "将显示给其他人。",
        "welcome.placeholder": "例：小明、爸爸、组长",
        "welcome.start": "开始",
        "delegation.sentStatus": "的任务状态",
        "delegation.sentTitle": "已发送任务面板",
        "delegation.emptyMsg": "还没有发送给他人的任务。",
        "delegation.emptyHint": "从主列表中选择项目，点击[分享]发送链接。",
        "delegation.pendingLabel": "⏳ 等待接收（未确认）",
        "delegation.progress": "项已完成",
        "received.fromSender": "的任务",
        "received.inboxTitle": "收件箱（收到的任务）",
        "received.emptyMsg": "还没有收到他人的任务。",
        "received.emptyHint": "当有人通过分享链接指定您为负责人时，任务将显示在这里。",
        "install.download": "安装应用",
        "time.overdue": "已过期",
        "time.soon": "即将截止",
        "time.minutesLeft": "分钟剩余",
        "time.hoursMinutesLeft": "小时{m}分剩余",
        "time.hoursLeft": "小时剩余",
        "time.daysHoursLeft": "天{h}小时剩余",
        "time.daysLeft": "天剩余",
        "page.welcome": "欢迎 👋",
        "page.welcomeDesc": "主屏幕应用（或新浏览器）。",
        "page.welcomeAsk": "您想如何开始？",
        "page.newTodo": "创建新工作空间",
        "page.or": "或",
        "page.joinTitle": "连接现有工作空间（恢复同步）",
        "page.joinDesc": "粘贴从其他浏览器复制的工作空间URL。",
        "page.joinPlaceholder": "例: https://.../?w=...",
        "page.joinBtn": "连接",
        "page.invalidUrl": "无效的工作空间URL或ID。",
    },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [lang, setLangState] = useState<Language>("ko");

    useEffect(() => {
        const stored = localStorage.getItem("your-todo-lang") as Language | null;
        if (stored && translations[stored]) {
            setLangState(stored);
        }
    }, []);

    const setLang = useCallback((newLang: Language) => {
        setLangState(newLang);
        localStorage.setItem("your-todo-lang", newLang);
    }, []);

    const t = useCallback((key: string): string => {
        return translations[lang]?.[key] || translations["ko"]?.[key] || key;
    }, [lang]);

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}
